"""
FastAPI REST API service for the medical multi-agent system.
Exposes query routing, synchronous analysis, and asynchronous background jobs.
"""

import os
import sys
import uuid
import json
import logging
import threading
import traceback
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from fastapi import FastAPI, BackgroundTasks, HTTPException, status
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

# Load environment variables: .env.dev first (dev-specific), then .env (base)
try:
    from dotenv import load_dotenv as _load_dotenv
    import pathlib as _pathlib

    _repo_root = _pathlib.Path(__file__).parent
    _load_dotenv(_repo_root / ".env.dev", override=False)  # dev-specific vars
    _load_dotenv(_repo_root / ".env", override=False)       # base vars (don't overwrite)
except ImportError:
    pass  # python-dotenv not installed, rely on shell environment

# Import agent router functions and models
from router import route_agent, sample_agents, DEFAULT_ROUTING_MODEL
from run_analysis import AgentOrchestrator
from llm_integrations import get_available_models

# Configure logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("medical_api")

app = FastAPI(
    title="Medical Multi-Agent API",
    description=(
        "REST API service for classifying medical queries and invoking specialized "
        "medical agents (Medication, Procedure, Diagnostic, and Fact Checker)."
    ),
    version="0.1.0"
)

# Ensure outputs directory exists and serve files statically
os.makedirs("outputs", exist_ok=True)
app.mount("/outputs", StaticFiles(directory="outputs"), name="outputs")


class JobStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


# In-memory thread-safe storage for asynchronous jobs
jobs_lock = threading.Lock()
jobs: Dict[str, Dict[str, Any]] = {}


class RouteRequest(BaseModel):
    query: str = Field(..., description="The query to be routed to a specialized agent.")
    model: str = Field(DEFAULT_ROUTING_MODEL, description="LLM model identifier to use for routing.")


class AnalyzeRequest(BaseModel):
    query: str = Field(..., description="The medical query/subject to analyze.")
    model: str = Field(DEFAULT_ROUTING_MODEL, description="LLM model to use for analysis.")
    implementation: str = Field("langchain", description="Agent implementation to use ('original' or 'langchain').")
    web_search: bool = Field(True, description="Whether to enable web search for the agent.")
    timeout: int = Field(300, description="LLM API timeout in seconds.")


def load_json_result(agent_id: str, files: Dict[str, str]) -> Dict[str, Any]:
    """
    Helper function to load the primary JSON results generated by each agent.
    """
    key_map = {
        "diagnostic_agent": "json_session",
        "procedure_agent": "result",
        "general_agent": "session",
        "medication_agent": "result"
    }
    key = key_map.get(agent_id)
    if not key or key not in files:
        return {}

    file_path = files[key]
    if os.path.exists(file_path):
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            logger.error(f"Error loading JSON result from {file_path}: {e}")
            return {"error": f"Failed to parse JSON file: {e}"}
    return {"warning": f"JSON result file not found at {file_path}"}


def execute_analysis_sync(
    query: str,
    model: str,
    implementation: str,
    web_search: bool,
    timeout: int
) -> Dict[str, Any]:
    """
    Runs the full routing and execution pipeline synchronously.
    """
    # Map model name to provider name
    available_models_dict = get_available_models()
    llm_provider = available_models_dict.get(model, model)

    # 1. Route the query
    logger.info(f"Routing query: '{query}' using model '{model}'")
    routed_agent_id = route_agent(
        query,
        sample_agents,
        default_agent_id="general_agent",
        model=model
    )
    logger.info(f"Routed query to agent: {routed_agent_id}")

    # 2. Run the specialized agent via AgentOrchestrator
    orchestrator = AgentOrchestrator(output_dir="outputs")
    files = {}

    if routed_agent_id == "medication_agent":
        _, files = orchestrator.run_medication_analyzer(
            medication=query,
            indication=None,
            other_medications=None,
            llm_provider=llm_provider,
            timeout=timeout,
            implementation=implementation,
            enable_web_research=web_search,
        )
    elif routed_agent_id == "procedure_agent":
        _, files = orchestrator.run_procedure_analyzer(
            procedure=query,
            details="API Request",
            llm_provider=llm_provider,
            timeout=timeout,
            implementation=implementation,
            enable_web_research=web_search,
        )
    elif routed_agent_id == "diagnostic_agent":
        _, files = orchestrator.run_diagnostic_analyzer(
            query=query,
            llm_provider=llm_provider,
            timeout=timeout,
            interactive=False,
        )
    elif routed_agent_id == "general_agent":
        _, files = orchestrator.run_fact_checker(
            subject=query,
            context="",
            llm_provider=llm_provider,
            timeout=timeout,
            implementation=implementation,
            enable_web_research=web_search,
        )
    else:
        raise ValueError(f"Unknown routed agent: {routed_agent_id}")

    # Load result data from file
    loaded_data = load_json_result(routed_agent_id, files)

    return {
        "agent_id": routed_agent_id,
        "files": files,
        "result": loaded_data
    }


def run_background_job(
    job_id: str,
    query: str,
    model: str,
    implementation: str,
    web_search: bool,
    timeout: int
):
    """
    Worker task for executing an analysis asynchronously in the background.
    """
    logger.info(f"Starting background job: {job_id}")
    with jobs_lock:
        jobs[job_id]["status"] = JobStatus.RUNNING
        jobs[job_id]["updated_at"] = datetime.now()

    try:
        data = execute_analysis_sync(
            query=query,
            model=model,
            implementation=implementation,
            web_search=web_search,
            timeout=timeout
        )
        with jobs_lock:
            jobs[job_id]["status"] = JobStatus.COMPLETED
            jobs[job_id]["agent_id"] = data["agent_id"]
            jobs[job_id]["files"] = data["files"]
            jobs[job_id]["result"] = data["result"]
            jobs[job_id]["updated_at"] = datetime.now()
        logger.info(f"Successfully completed background job: {job_id}")
    except Exception as e:
        tb = traceback.format_exc()
        logger.error(f"Failed background job: {job_id}. Error: {e}")
        with jobs_lock:
            jobs[job_id]["status"] = JobStatus.FAILED
            jobs[job_id]["error"] = f"{e}\n{tb}"
            jobs[job_id]["updated_at"] = datetime.now()


@app.get("/health")
def health_endpoint():
    """
    Status endpoint. Returns status, time, and default routing model.
    """
    return {
        "status": "healthy",
        "timestamp": datetime.now().isoformat(),
        "default_model": DEFAULT_ROUTING_MODEL
    }


@app.get("/agents")
def list_agents_endpoint():
    """
    List all routable medical agents and their specs.
    """
    return [
        {
            "id": agent.id,
            "name": agent.name,
            "description": agent.description,
            "routing_notes": agent.routing_notes
        }
        for agent in sample_agents
    ]


@app.get("/models")
def list_models_endpoint():
    """
    List available models and their mapped providers.
    """
    try:
        return get_available_models()
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error retrieving models: {e}"
        )


@app.post("/route")
def route_query_endpoint(req: RouteRequest):
    """
    Classify a medical query and return the selected agent without running the analysis.
    """
    try:
        routed_agent_id = route_agent(
            req.query,
            sample_agents,
            default_agent_id="general_agent",
            model=req.model
        )
        agent = next((a for a in sample_agents if a.id == routed_agent_id), None)
        return {
            "query": req.query,
            "agent_id": routed_agent_id,
            "agent_name": agent.name if agent else "Unknown Agent"
        }
    except Exception as e:
        logger.error(f"Error during query routing: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Routing failure: {e}"
        )


@app.post("/analyze")
def analyze_query_sync_endpoint(req: AnalyzeRequest):
    """
    Synchronously route and analyze a medical query. Blocks until analysis completes.
    """
    try:
        res = execute_analysis_sync(
            query=req.query,
            model=req.model,
            implementation=req.implementation,
            web_search=req.web_search,
            timeout=req.timeout
        )
        return {
            "status": "success",
            "query": req.query,
            "agent_id": res["agent_id"],
            "files": res["files"],
            "result": res["result"]
        }
    except Exception as e:
        logger.error(f"Error during synchronous analysis execution: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Analysis execution failure: {e}"
        )


@app.post("/analyze/async", status_code=status.HTTP_202_ACCEPTED)
def analyze_query_async_endpoint(req: AnalyzeRequest, background_tasks: BackgroundTasks):
    """
    Asynchronously route and analyze a medical query. Returns a job ID to poll for status.
    """
    job_id = str(uuid.uuid4())
    now = datetime.now()

    with jobs_lock:
        jobs[job_id] = {
            "id": job_id,
            "query": req.query,
            "agent_id": None,
            "status": JobStatus.PENDING,
            "created_at": now,
            "updated_at": now,
            "error": None,
            "files": None,
            "result": None
        }

    background_tasks.add_task(
        run_background_job,
        job_id=job_id,
        query=req.query,
        model=req.model,
        implementation=req.implementation,
        web_search=req.web_search,
        timeout=req.timeout
    )

    return {
        "job_id": job_id,
        "status": JobStatus.PENDING,
        "check_status_url": f"/jobs/{job_id}"
    }


@app.get("/jobs/{job_id}")
def get_job_status_endpoint(job_id: str):
    """
    Retrieve status and result of a background job.
    """
    with jobs_lock:
        job = jobs.get(job_id)

    if not job:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Job not found"
        )

    return job


def main():
    """Entry point for medical-api console script."""
    import argparse
    import uvicorn

    parser = argparse.ArgumentParser(description="Medical Multi-Agent API Service")
    parser.add_argument("--host", default="127.0.0.1", help="Host address to bind to (default: 127.0.0.1)")
    parser.add_argument("--port", type=int, default=8000, help="Port to bind to (default: 8000)")
    parser.add_argument("--reload", action="store_true", help="Enable auto-reload for development")

    args = parser.parse_args()

    uvicorn.run("api:app", host=args.host, port=args.port, reload=args.reload)


if __name__ == "__main__":
    main()
